name: Repo Dispatcher
on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:
    #ref: refs/heads/main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - name: Trigger Compile
          run: |
            curl \
            -X POST https://api.github.com/repos/${{ github.repository }}/actions/workflows/7106172/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.workflow_token }}" \
            -d '{"ref": "master", "inputs": {"device": "r2s"}}'
